status = [
  "ci 1.7.0 - ubuntu-latest",
  "ci 1.7.0 - windows-latest",
  "ci 1.7.0 - macOS-latest",
  "format",
  "docbuild"
]
delete_merged_branches = true
timeout_sec = 12600
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
